version: "3.9"

services:
    php:
        build:
            context: .
            target: app_php
            args:
                SYMFONY_VERSION: ${SYMFONY_VERSION:-}
                STABILITY: ${STABILITY:-stable}
        restart: unless-stopped

    nginx:
        build:
            context: .
            target: app_nginx
        depends_on:
            - php
        links:
            - php
        restart: unless-stopped
        volumes:
            - ./public:/srv/app/public:ro
        ports:
            # HTTP
            -   target: 80
                published: ${HTTP_PORT:-80}
                protocol: tcp
            # HTTPS
            -   target: 443
                published: ${HTTPS_PORT:-443}
                protocol: tcp
